[package]
name = "fs-unpack"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
argh = "0.1.13"
fs-lib = { version = "1.0.0", path = "../fs-lib" }
gar-lib = { git = "https://github.com/Paint-a-Farm/gar-lib.git" }
rayon = "1.11.0"
